/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package academia;

import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author victo
 */
public class AdicionarPersonais extends javax.swing.JFrame {

    /**
     * Creates new form TabelaPersonais
     */
    public AdicionarPersonais() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPersonais = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nomePersonal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cpfPersonal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        crtPersonal = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        mensagem = new javax.swing.JLabel();
        del = new javax.swing.JButton();

        tabelaPersonais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "CRT"
            }
        ));
        jScrollPane1.setViewportView(tabelaPersonais);

        jLabel1.setText("Nome Personal");

        jLabel2.setText("CPF");

        cpfPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfPersonalActionPerformed(evt);
            }
        });

        jLabel3.setText("CRT");

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        update.setText("Atualizar");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jLabel4.setText("Lista Personais");

        del.setText("Deletar");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(add)
                        .addGap(18, 18, 18)
                        .addComponent(update)
                        .addGap(18, 18, 18)
                        .addComponent(del))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cpfPersonal)
                            .addComponent(nomePersonal, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(crtPersonal))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(mensagem))
                .addGap(0, 47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomePersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cpfPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(crtPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(update)
                    .addComponent(del))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cpfPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfPersonalActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        mensagem.setText("");
        DefaultTableModel tabela = (DefaultTableModel) tabelaPersonais.getModel();
        if(!nomePersonal.getText().trim().equals("")){
        tabela.addRow(new Object[]{nomePersonal.getText(),cpfPersonal.getText(),crtPersonal.getText()});
        }
        else{
            mensagem.setText("Nenhum campo pode ser deixado em branco");
        }
    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
         mensagem.setText("");
        DefaultTableModel tabela = (DefaultTableModel) tabelaPersonais.getModel();
        if (tabelaPersonais.getSelectedRow()== -1){
            if(tabelaPersonais.getRowCount() == 0){
                mensagem.setText("A tabela está vazia");
            }
            else{
                mensagem.setText("Você precisa selecionar um personal");
            }

        }
        else{
            tabelaPersonais.setValueAt(nomePersonal.getText(), tabelaPersonais.getSelectedRow(), 0);
            tabelaPersonais.setValueAt(cpfPersonal.getText(), tabelaPersonais.getSelectedRow(), 1);
            tabelaPersonais.setValueAt(crtPersonal.getText(), tabelaPersonais.getSelectedRow(), 2);

        }
    }//GEN-LAST:event_updateActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tabela = (DefaultTableModel) tabelaPersonais.getModel();
         if (tabelaPersonais.getSelectedRow()== -1){
            if(tabelaPersonais.getRowCount() == 0){
                mensagem.setText("A tabela está vazia");
            }
            else{
                mensagem.setText("Você precisa selecionar um personal");
            }
           
         }
         else{
          tabela.removeRow(tabelaPersonais.getSelectedRow());
          
         }
         
         
    }//GEN-LAST:event_delActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarPersonais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarPersonais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarPersonais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarPersonais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarPersonais().setVisible(true);
            }
        });
    }

    public JTextField getCpfPersonal() {
        return cpfPersonal;
    }

    public void setCpfPersonal(JTextField cpfPersonal) {
        this.cpfPersonal = cpfPersonal;
    }

    public JTextField getCrtPersonal() {
        return crtPersonal;
    }

    public void setCrtPersonal(JTextField crtPersonal) {
        this.crtPersonal = crtPersonal;
    }

    public JTextField getNomePersonal() {
        return nomePersonal;
    }

    public void setNomePersonal(JTextField nomePersonal) {
        this.nomePersonal = nomePersonal;
    }

    public JTable getTabelaPersonais() {
        return tabelaPersonais;
    }

    public void setTabelaPersonais(JTable tabelaPersonais) {
        this.tabelaPersonais = tabelaPersonais;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField cpfPersonal;
    private javax.swing.JTextField crtPersonal;
    private javax.swing.JButton del;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mensagem;
    private javax.swing.JTextField nomePersonal;
    private javax.swing.JTable tabelaPersonais;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
